# Generated by Django 3.2.2 on 2021-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.FloatField(verbose_name='Total Money'),
        ),
    ]
